### ISSUE TITLE
extract out the operational documentation

### ISSUE THREAD

**Issue by goern** [operate-first/continuous-delivery#1]
As an Operator of a CI/CD pipeline,
I want to read thru a doc,
so that I can deploy all the components of the op1st ci/cd pipeline
and so that I can run all the bots for my developers

**Comment by harshad16** [comment]
Does this document suffice the requirment : https://github.com/AICoE/aicoe-ci/blob/master/docs/how-to-contribute.md
or should i work on one in this repository?

**Comment by goern** [comment]
> Does this document suffice the requirment : https://github.com/AICoE/aicoe-ci/blob/master/docs/how-to-contribute.md
> or should i work on one in this repository?

I would say, lets move the docs from aicoe-ci into this repo, lets replace aicoe-ci with op1st-ci and have aicoe-ci link to this repo, that way, we will also get a nice website: https://operate-first.github.io/continuous-delivery/continuous_delivery
