### ISSUE TITLE
Onboard Project AICoE

### ISSUE THREAD

**Issue by isabelizimm** [operate-first/continuous-delivery#11]
**Do you need a project on AICoE org in Quay.io?**
Yes. I need to create a project on quay.io/aicoe to create JupyterHub images for the project "Pet Image Detection" and deploy on MOC operate-first cluster.

**Detail required for the setup:**
Please describe the following requirements.
_Repository Name_: pet-image-detection
_GitHub Repository associated_: <https://github.com/aicoe-aiops/pet-image-detection>
_UserId of users requiring Admin Access_: izimmerm

**Comment by tumido** [comment]
/cc @harshad16 are these kind of requests expected to be handled by bots?

If yes, @sesheta is not doing anything, can you please look into it?
If this should be performed by a human instead, let's change the default assignment.

**Comment by harshad16** [comment]
These were to be handle by the bots, however, the work to program the bot got delayed a bit. 
I will remove the default assignment till the bot is ready for this.
Thanks @tumido

**Comment by harshad16** [comment]
Hello @isabelizimm ,

The project is ready for you to use https://quay.io/repository/aicoe/pet-image-detection
Also, an invite was sent to you to join the org in quay.io.
please check if this is satisfactory.

**Comment by isabelizimm** [comment]
Looks great! Thank you so much 👍
