### ISSUE TITLE
Onboard Project AICoE

### ISSUE THREAD

**Issue by Jooho** [operate-first/continuous-delivery#12]
**Do you a project on AICoE org in Quay.io?**
No

**Detail required for the setup:**
Please describe the following requirements.
_Repository Name_: s2i-pachyderm-notebook
_GitHub Repository associated_: https://github.com/Jooho/s2i-pachyderm-notebook.git
_UserId of users requiring Admin Access_: jlee

**Comment by 4n4nd** [comment]
@Jooho do you need a repository in the quay.io/aicoe org?
If so, @harshad16 might be able to help you.

**Comment by Jooho** [comment]
No at this moment but eventually, I believe I need it.

This is just testing purpose and he already added my secret for CI robot :)

**Comment by HumairAK** [comment]
@Jooho I guess what we're wondering is, what you're looking to be onboarded for?

**Comment by Jooho** [comment]
@HumairAK 
I am following this [doc](https://www.operate-first.cloud/users/data-science-workflows/docs/create_and_deploy_jh_image.md) and the video clip ask to create this onboard issue :)
Actually, I am not sure what this onboard issue is for. just tried to create like other onboard issues.

What I am trying now is that I fully follow the process to use AICOE-CI. Whenever a new ISV vendor engaged, I believe I need to create a custom jupyter notebook. For the custom jupyter notebook repo, I want to use AICOE-CI to build a new image automatically. 

After I follow all process, I would like to document the flows for ISV and team. Could you explain what this onboard project issue is for and when I need to create this?

**Comment by harshad16** [comment]
This is onboard issue is for requesting a repository on aicoe org on quay.io

while using aicoe-ci, we provide this option, so the data-scientist has to interact less with component. 
they can request a repo and directly use it in the config file.
