### ISSUE TITLE
Onboard Project AICoE

### ISSUE THREAD

**Issue by erikerlandson** [operate-first/continuous-delivery#14]
**Do you a project on AICoE org in Quay.io?**
Yes

**Detail required for the setup:**
Please describe the following requirements.
_Repository Name_: op1st-pipeline-demo
_GitHub Repository associated_: https://github.com/erikerlandson/op1st-pipeline-demo
_UserId of users requiring Admin Access_: sesheta, erikerlandson

**Comment by harshad16** [comment]
The aicoe repos are created for you: https://quay.io/repository/aicoe/op1st-pipeline-demo
also, an invite is sent out for the quay repo access to your user account.

**Comment by erikerlandson** [comment]
@harshad16  thanks!  I am also now on the aicoe quay org.
