### ISSUE TITLE
Onboard Project AICoE

### ISSUE THREAD

**Issue by MichaelClifford** [operate-first/continuous-delivery#16]
**Do you a project on AICoE org in Quay.io?**
yes

**Detail required for the setup:**
Please describe the following requirements.
_Repository Name_: summit-2021-octo-keynote
_GitHub Repository associated_: https://github.com/AICoE/summit-2021-octo-keynote
_UserId of users requiring Admin Access_: michaelclifford

**Comment by harshad16** [comment]
The repository is now available: https://quay.io/repository/aicoe/summit-2021-octo-keynote
Also given `michaelclifford admin` access to the repo.
please close the issue, if this suffice.

**Comment by MichaelClifford** [comment]
thanks!
/close
