### ISSUE TITLE
Onboard Project AICoE

### ISSUE THREAD

**Issue by antter** [operate-first/continuous-delivery#18]
**Do you a project on AICoE org in Quay.io?**
No. My project is in my individual quay repository at the moment.

**Detail required for the setup:**
Please describe the following requirements.
_Repository Name_: github-labeler
_GitHub Repository associated_: https://github.com/aicoe-aiops/github-labeler
_UserId of users requiring Admin Access_: antter

@MichaelClifford I was told I should tag mentors

**Comment by MichaelClifford** [comment]
Who is responsible for creating this quay project?

**Comment by harshad16** [comment]
@MichaelClifford , we were planning on making this automated 
however we had some reservations, so automation is on hold.

i will be taking care of this issue

**Comment by harshad16** [comment]
The quay repo is created: https://quay.io/repository/aicoe/github-labeler?tab=tags
user `antter` couldn't be found to make the admin
@MichaelClifford  have made you the admin of the repo
please feel free to add others. 

close the issue, if the repo seems apt.

**Comment by antter** [comment]
> The quay repo is created: https://quay.io/repository/aicoe/github-labeler?tab=tags user `antter` couldn't be found to make the admin @MichaelClifford have made you the admin of the repo please feel free to add others.
> 
> close the issue, if the repo seems apt.

My quay userId is atersaak, sorry

**Comment by harshad16** [comment]
invite to atersaak is sent for being the member in aicoe repo :+1:
