### ISSUE TITLE
Onboard Project AICoE

### ISSUE THREAD

**Issue by aakankshaduggal** [operate-first/continuous-delivery#20]
**Do you want a new repository in the AICoE org created on Quay.io?**
Yes

**Detail required for the setup:**
Please describe the following requirements.
_Repository Name_: data-science-workflows
_GitHub Repository associated_: https://github.com/aicoe-aiops/data-science-workflows/
_UserId of users requiring Admin Access_: sesheta , @MichaelClifford 

cc- @harshad16

**Comment by harshad16** [comment]
The repos is created: https://quay.io/repository/aicoe/data-science-workflows?tab=tags
please close the issue, if the repo seems apt.

**Comment by aakankshaduggal** [comment]
Thank you @harshad16 :smile:
