### ISSUE TITLE
Onboard Project github-bot

### ISSUE THREAD

**Issue by antter** [operate-first/continuous-delivery#21]
**Do you want a new repository in the AICoE org created on Quay.io?**
Yes

I new a different image for the bot that will actually be doing the tagging. The bot code will be under the same repository and I will use overlays so two different images are built. Using https://github.com/thoth-station/solver/ as a guide and seems like I need a different repository on quay for each image.

**Detail required for the setup:**
Please describe the following requirements.
_Repository Name_: github-labeler-bot
_GitHub Repository associated_: https://github.com/aicoe-aiops/github-labeler
_UserId of users requiring Admin Access_: atersaak

@MichaelClifford

**Comment by antter** [comment]
@harshad16

**Comment by harshad16** [comment]
This repo is now created: https://quay.io/repository/aicoe/github-labeler-bot?tab=info
