### ISSUE TITLE
Re-encrypt the signing-secret with updated .sops file

### ISSUE THREAD

**Issue by harshad16** [operate-first/continuous-delivery#23]
**Describe the bug**

The encrypted file is missing the maintainer gpg key, because of which maintainers cant decrypt it.
this would cause issues in the future  maintenance 

Requires re-encryption of https://github.com/operate-first/continuous-delivery/blob/master/tekton-chains/overlays/moc/tekton-chains-secret.enc.yaml

**Expected behavior**
Easy decryption of the secret.

**Comment by harshad16** [comment]
cc: @cooktheryan 
can you please re-encrypt the file with the updated gpg key in the .sops.yaml
please include your key as well in the .sops.yaml

**Comment by cooktheryan** [comment]
@harshad16 yep will do tomorrow. I'm going back through and just making sure all the pieces work together connaisseur + cosign
