### ISSUE TITLE
Onboard Project AICoE

### ISSUE THREAD

**Issue by Shreyanand** [operate-first/continuous-delivery#25]
**Do you want a new repository in the AICoE org created on Quay.io?**
Yes

**Detail required for the setup:**
Please describe the following requirements.
_Repository Name_: operate-first-jupyterhub-analysis
_GitHub Repository associated_: https://github.com/aicoe-aiops/operate-first-jupyterhub-analysis
_UserId of users requiring Admin Access_: @Shreyanand, @MichaelClifford

**Comment by harshad16** [comment]
Here is the repo: https://quay.io/repository/aicoe/operate-first-jupyterhub-analysis?tab=info
close the issue, if this feels statisfactory.
