### ISSUE TITLE
Onboard Project AICoE

### ISSUE THREAD

**Issue by aakankshaduggal** [operate-first/continuous-delivery#29]
**Do you want a new repository in the AICoE org created on Quay.io?**
Yes

**Detail required for the setup:**
Please describe the following requirements.
_Repository Name_: ocp-ci-analysis
_Image Name_ - optimal-stopping-point
_GitHub Repository associated_: https://github.com/aicoe-aiops/ocp-ci-analysis
_UserId of users requiring Admin Access_: <sesheta> , @aakankshaduggal , @chauhankaranraj

**Comment by harshad16** [comment]
The project is created:https://quay.io/repository/aicoe/optimal-stopping-point.
cant add alll folks suggested as admin, as you are not a part of aicoe org in quay
already shared a invite, you should have it in quay.
accept it and you would admin.


close the issue if satisfied.

**Comment by aakankshaduggal** [comment]
Thank you @harshad16 :+1:
