### ISSUE TITLE
Onboard Project AICoE

### ISSUE THREAD

**Issue by suppathak** [operate-first/continuous-delivery#32]
**Do you want a new repository in the AICoE org created on Quay.io?**
Yes

**Detail required for the setup:**
Please describe the following requirements.
_Repository Name_: htm-applications
_GitHub Repository associated_: https://github.com/aicoe-aiops/HTM-applications
_UserId of users requiring Admin Access_: @supathak @MichaelClifford

**Comment by harshad16** [comment]
repository name can't be uppercase, changed it to lowercase. 
here is the repository: https://quay.io/repository/aicoe/htm-applications?tab=info

also, we need your quay userid to add you to aicoe repo. 
please share that, we have already added @MichaelClifford  as admin for this repo.

**Comment by suppathak** [comment]
@harshad16 , I have updated the issue with quay username and repo-name . Please check the changes. Thanks :)

**Comment by harshad16** [comment]
@suppathak  invitation is sent for you to join the aicoe team on quay.

**Comment by harshad16** [comment]
Done.
