### ISSUE TITLE
Onboard Project AICoE

### ISSUE THREAD

**Issue by chauhankaranraj** [operate-first/continuous-delivery#33]
**Do you want a new repository in the AICoE org created on Quay.io?**
Yes

**Detail required for the setup:**
Please describe the following requirements.
_Repository Name_: metrics
_GitHub Repository associated_: https://github.com/open-services-group/metrics
_UserId of users requiring Admin Access_: kachau, shanand, hveeradh

**Comment by chauhankaranraj** [comment]
Related to open-services-group/metrics#41

**Comment by harshad16** [comment]
Seems like this is affiliated with open-services-group
i will add it under https://quay.io/organization/open-services-group?tab=repos

**Comment by harshad16** [comment]
The repo is created here: https://quay.io/repository/open-services-group/metrics?namespace=open-services-group
and all the people mentioned in the issue, have been sent invite for the org

**Comment by chauhankaranraj** [comment]
Thank you @harshad16! :grinning:
