### ISSUE TITLE
add documentation "how to build a ODH jupyterhub image"

### ISSUE THREAD

**Issue by goern** [operate-first/continuous-delivery#4]
**Is your feature request related to a problem? Please describe.**

describe what an Data Scientist needs to do, to get his image build (by AICoE-CI) and published (to op1st-odh)

**Comment by martinpovolny** [comment]
Does this: https://www.operate-first.cloud/users/data-science-workflows/docs/create_and_deploy_jh_image.md (at least partly) address this issue?

What is "op1st-odh"? I would probably need to a step to address the 'published to op1st-odh' part.
