### ISSUE TITLE
Onboard Project AICoE

### ISSUE THREAD

**Issue by 4n4nd** [operate-first/continuous-delivery#5]
**Do you a project on AICoE org in Quay.io?** 
Yes. Project should be public. using this [aicoe-ci config file](https://github.com/aicoe-aiops/cloud-price-analysis-public/blob/master/.aicoe-ci.yaml#L13)

**Detail required for the setup:** 
Please describe the following requirements. 
_Repository Name_: cloud-price-analysis
_GitHub Repository associated_: https://github.com/aicoe-aiops/cloud-price-analysis-public
_UserId of users requiring Admin Access_: 4n4nd

**Comment by 4n4nd** [comment]
cc @aakankshaduggal

**Comment by harshad16** [comment]
welcome aboard : https://quay.io/repository/aicoe/cloud-price-analysis
close the issue, if this is satisfactory.

**Comment by 4n4nd** [comment]
This is perfect! Thanks!
