### ISSUE TITLE
Onboard Project AICoE

### ISSUE THREAD

**Issue by chauhankaranraj** [operate-first/continuous-delivery#7]
**Do you need a project on AICoE org in Quay.io?**
Yes, I need to create a project on quay.io/aicoe to create JupyterHub images for the project "OpenShift Anomaly Detection" and deploy on MOC operate-first cluster.

**Detail required for the setup:**
Please describe the following requirements.
_Repository Name_: openshift-anomaly-detection
_GitHub Repository associated_: https://github.com/aicoe-aiops/openshift-anomaly-detection
_UserId of users requiring Admin Access_: kachau

I think @MichaelClifford and @martinpovolny would want access too, but I'm not sure of their user id's

**Comment by harshad16** [comment]
The project is created and available https://quay.io/repository/aicoe/openshift-anomaly-detection?tab=info
you have been provided admin access, so you would be able to add people with different permission to access this project repo. 
please close the issue, if this suffice.

**Comment by chauhankaranraj** [comment]
Thanks @harshad16 :)
