### ISSUE TITLE
Onboard Project AICoE

### ISSUE THREAD

**Issue by tumido** [operate-first/continuous-delivery#9]
**Do you a project on AICoE org in Quay.io?**
What a question! :smile: That's why I'm opening this ticket, duh! :smile:

I'm setting up a CI build for yet-another-jupyternb-image repo.  

**Detail required for the setup:**
Please describe the following requirements.
_Repository Name_: mailing-list-analysis-toolkit
_GitHub Repository associated_: https://github.com/aicoe-aiops/mailing-list-analysis-toolkit
_UserId of users requiring Admin Access_: sesheta, tcoufal

**Comment by harshad16** [comment]
The repository is now available https://quay.io/repository/aicoe/mailing-list-analysis-toolkit
please close the issue, this feels satisfactory.

**Comment by tumido** [comment]
Thank you very much, sir! :+1: :rocket:
